server {
    server_name localhost;
    client_max_body_size 1000M;
    listen NGINX_PORT;

    index index.html index.php;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www;

    location / {
        # Allow CORS headers
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';

        # Disable caching
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache';
        if_modified_since off;
        expires off;
        etag off;

        # Serve static files directly, otherwise pass to index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Allow CORS headers
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';

        # Ensure PHP scripts exist before passing to FastCGI
        try_files $uri =404;

        # Pass PHP requests to FastCGI
        fastcgi_pass php:php_service;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Increase timeouts
        fastcgi_read_timeout 300;
        proxy_read_timeout 300;
    }
}